In [1]:
import numpy as np
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

In [2]:
glove_embeddings = WordEmbeddings('glove') #context independent

2021-05-05 22:17:46,355 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to C:\Users\Varun\AppData\Local\Temp\tmpb56bjket


100%|█████████████████████████████████████████████████████████████████| 160000128/160000128 [02:40<00:00, 994861.19B/s]

2021-05-05 22:20:34,477 copying C:\Users\Varun\AppData\Local\Temp\tmpb56bjket to cache at C:\Users\Varun\.flair\embeddings\glove.gensim.vectors.npy


2021-05-05 22:20:34,861 removing temp file C:\Users\Varun\AppData\Local\Temp\tmpb56bjket
2021-05-05 22:20:36,079 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to C:\Users\Varun\AppData\Local\Temp\tmppofv8cpq


100%|███████████████████████████████████████████████████████████████████| 21494764/21494764 [00:25<00:00, 857046.84B/s]

2021-05-05 22:21:02,703 copying C:\Users\Varun\AppData\Local\Temp\tmppofv8cpq to cache at C:\Users\Varun\.flair\embeddings\glove.gensim


2021-05-05 22:21:02,823 removing temp file C:\Users\Varun\AppData\Local\Temp\tmppofv8cpq


In [6]:
sentence_1 = Sentence('apple released iphone 12 pro max in 2020')

In [22]:
glove_embeddings.embed(sentence_1)

[Sentence: "apple released iphone 12 pro max in 2020"   [− Tokens: 8]]

In [23]:
for token in sentence_1:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,

In [33]:
sentence_1[0]

Token: 1 apple

In [34]:
sentence_1[0].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [26]:
sentence_1[5].embedding.shape

torch.Size([100])

In [19]:
sentence_2 = Sentence('an apple a day keeps the doctor away')

In [28]:
glove_embeddings.embed(sentence_2)

[Sentence: "an apple a day keeps the doctor away"   [− Tokens: 8]]

In [29]:
for token in sentence_2:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0

In [30]:
sentence_2[1]

Token: 2 apple

In [31]:
sentence_2[1].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [32]:
sentence_2[1].embedding.shape

torch.Size([100])

In [35]:
glove_dist = distance.euclidean(np.array(sentence_1[0].embedding),
                                np.array(sentence_2[1].embedding))

In [36]:
print("Distance between apple embeddings for Glove = {}".format(glove_dist))

Distance between apple embeddings for Glove = 0.0


In [2]:
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/714M [00:00<?, ?B/s]

In [12]:
bert_embedding.embed(sentence_1)

[Sentence: "apple released iphone 12 pro max in 2020"   [− Tokens: 8]]

In [13]:
for token in sentence_1:
    print(token)
    print(token.embedding)

Token: 1 apple
tensor([-4.0002e-01, -7.5034e-01,  1.3564e+00, -1.8190e-01, -4.7752e-01,
         5.3768e-01, -1.2345e+00, -3.4001e-01, -5.4844e-01,  4.4100e-01,
         2.5293e-01, -1.4467e+00, -1.1097e+00,  2.7784e-01, -2.2182e-01,
         3.5588e-01, -6.7693e-01, -4.0594e-01, -6.3365e-01, -3.5430e-01,
         1.8716e-01,  6.6553e-01, -6.1339e-01, -3.2032e-01,  1.2472e+00,
         1.6040e-01,  8.6434e-01,  5.2188e-01,  5.0738e-01,  1.4972e-01,
        -7.2835e-01, -6.2481e-02, -8.2694e-02,  1.1184e+00,  4.4343e-01,
        -3.1557e-01, -6.9858e-01,  2.9364e-01, -2.3869e-01, -1.4881e+00,
        -2.8640e-01, -1.3705e+00,  8.9595e-01,  3.4610e-01, -4.2076e-01,
         1.6068e-01,  2.7630e-01,  6.4290e-01, -2.0239e-02, -2.4369e-01,
         3.5084e-01, -8.4700e-01,  2.5209e-01,  3.6158e-01, -4.7783e-01,
        -6.3383e-01,  3.8656e-01, -8.9556e-01, -8.8049e-01,  2.9823e-01,
         9.8012e-01,  2.4931e-01, -3.3962e-01, -3.5866e-01, -4.8118e-01,
        -2.3642e-02, -2.4308e-01, -2

In [14]:
sentence_1[0]

Token: 1 apple

In [16]:
sentence_1[0].embedding

tensor([-4.0002e-01, -7.5034e-01,  1.3564e+00, -1.8190e-01, -4.7752e-01,
         5.3768e-01, -1.2345e+00, -3.4001e-01, -5.4844e-01,  4.4100e-01,
         2.5293e-01, -1.4467e+00, -1.1097e+00,  2.7784e-01, -2.2182e-01,
         3.5588e-01, -6.7693e-01, -4.0594e-01, -6.3365e-01, -3.5430e-01,
         1.8716e-01,  6.6553e-01, -6.1339e-01, -3.2032e-01,  1.2472e+00,
         1.6040e-01,  8.6434e-01,  5.2188e-01,  5.0738e-01,  1.4972e-01,
        -7.2835e-01, -6.2481e-02, -8.2694e-02,  1.1184e+00,  4.4343e-01,
        -3.1557e-01, -6.9858e-01,  2.9364e-01, -2.3869e-01, -1.4881e+00,
        -2.8640e-01, -1.3705e+00,  8.9595e-01,  3.4610e-01, -4.2076e-01,
         1.6068e-01,  2.7630e-01,  6.4290e-01, -2.0239e-02, -2.4369e-01,
         3.5084e-01, -8.4700e-01,  2.5209e-01,  3.6158e-01, -4.7783e-01,
        -6.3383e-01,  3.8656e-01, -8.9556e-01, -8.8049e-01,  2.9823e-01,
         9.8012e-01,  2.4931e-01, -3.3962e-01, -3.5866e-01, -4.8118e-01,
        -2.3642e-02, -2.4308e-01, -2.3537e-01,  5.1

In [18]:
sentence_1[0].embedding.shape

torch.Size([768])

In [21]:
bert_embedding.embed(sentence_2)

for token in sentence_2:
    print(token)
    print(token.embedding)

Token: 1 an
tensor([-6.2131e-02, -5.6198e-01, -4.2689e-02,  7.2000e-02, -2.9765e-01,
        -7.1486e-01, -3.6600e-01, -1.3986e-01, -1.4300e-01,  8.1381e-01,
         1.1963e+00, -6.1581e-01,  3.6250e-01,  8.4150e-01, -4.4045e-02,
         2.8211e-02, -7.4547e-01, -7.8496e-01, -5.7974e-01,  2.5401e-01,
        -7.8643e-02, -6.4859e-01,  6.7312e-02,  4.4979e-01,  7.0135e-01,
         2.3977e-02,  4.9596e-01,  6.5418e-01, -3.8662e-01,  3.1053e-01,
         5.7482e-01, -9.2784e-02,  2.2797e-01,  4.4377e-01, -1.0632e-01,
         2.5218e-01,  7.7848e-01,  3.3691e-01,  2.4858e-01, -1.4443e+00,
         3.2681e-01, -4.8333e-01,  1.0783e-01,  6.6177e-02, -3.8333e-01,
         4.9409e-01, -3.1767e-01, -6.0186e-01, -2.2173e-01,  3.8336e-01,
        -2.3275e-02, -4.3788e-01,  2.5231e-01, -1.8277e-02,  5.6599e-01,
        -1.3647e-01, -1.0312e+00, -8.4567e-01, -7.2017e-01, -2.0784e-01,
         5.3433e-01,  6.9889e-01, -6.1807e-01,  5.8636e-02,  6.1643e-01,
        -9.8774e-02,  1.9702e-01, -2.84

In [22]:
sentence_2[1]

Token: 2 apple

In [23]:
sentence_2[1].embedding

tensor([-2.2119e-01, -2.6302e-01,  1.0284e+00,  2.9557e-01,  4.2195e-01,
         4.0977e-01, -1.0462e+00, -5.5866e-02, -6.6489e-01,  3.2660e-01,
        -9.6396e-02, -7.8063e-01, -1.0701e+00,  3.7100e-01,  2.7175e-01,
         6.5679e-01,  3.5125e-02, -4.6680e-02, -6.4241e-01, -3.0156e-01,
        -4.2065e-02,  4.0001e-01, -7.2056e-01, -4.9586e-01,  6.0750e-01,
         3.0532e-01,  7.3638e-01, -2.7222e-01,  7.4451e-01, -8.0054e-02,
        -1.0552e+00, -1.1012e-02, -5.4956e-02,  6.3087e-01, -5.6985e-02,
        -2.8401e-01, -1.5618e-01,  9.6237e-01, -1.7821e-01, -1.2285e+00,
        -2.3602e-01, -7.2758e-01,  3.9626e-01,  2.2330e-01,  2.6225e-01,
        -1.4417e-01, -4.2015e-01,  6.2624e-02, -1.7815e-01, -1.2370e+00,
        -5.2283e-02, -5.0073e-01,  9.9961e-01, -9.5513e-03, -1.0571e+00,
        -7.0368e-01,  6.7827e-01, -8.5790e-01, -7.2201e-01, -5.3299e-01,
         9.6342e-01,  8.4172e-02, -8.2697e-01, -3.4908e-01, -8.8854e-01,
        -6.1493e-01, -5.8640e-01, -2.8053e-01,  7.4

In [24]:
sentence_2[1].embedding.shape

torch.Size([768])

In [25]:
bert_dist = distance.euclidean(np.array(sentence_1[0].embedding),
                              np.array(sentence_2[1].embedding))

In [26]:
print("Distance between apple embeddings for Bert = {}".format(bert_dist))

Distance between apple embeddings for Bert = 11.685754776000977
